### ISSUE TITLE
"compiled against a different Node.js version" Error

### ISSUE THREAD

**Issue by FabiowQuixada** [hbenl/vscode-test-explorer#121]
Hello,

after installing "better-sqlite3", whenever I try to reload tests, I get the following message in Jasmine Explorer Log:

Worker: Caught error Error: The module '(...)/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using npm rebuild or npm install).
at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
at Module.load (internal/modules/cjs/loader.js:620:32)
at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
at Function.Module._load (internal/modules/cjs/loader.js:551:3)
at Module.require (internal/modules/cjs/loader.js:658:17)
at require (internal/modules/cjs/helpers.js:20:18)
at bindings (/home/fabiow/Development/Projects/isml-linter/node_modules/bindings/bindings.js:112:48)
at Object. ((...)/node_modules/better-sqlite3/lib/database.js:6:40)

I tried those suggestions and others, but none worked. Everything else seems to be working, including running tests manually.

If I uninstall that package, Jasmine Test Explorer starts working again.

Can you please help me with that?

Thank you!

**Comment by hbenl** [comment]
Since you can run your tests manually, my guess is that you use a different Node version in that case. Try setting `jasmineExplorer.nodePath` to the path of this Node version.
