### ISSUE TITLE
mocha.parallelMode is not a function

### ISSUE THREAD

**Issue by shy2net** [hbenl/vscode-test-explorer#183]
On the new version (2.9.0) it seems like the extension is crushing with following:

```
TypeError: mocha.parallelMode is not a function
    at /Users/shynet/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/out/worker/bundle.js:5722:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/shynet/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/out/worker/bundle.js:38:58)
```

**Comment by hbenl** [comment]
Fixed in version 2.9.1 of Mocha Test Explorer.
