### ISSUE TITLE
The extension Icon doesn't show on sidebar

### ISSUE THREAD

**Issue by alambertt** [hbenl/vscode-test-explorer#209]
I have the Go test Extension installed. Before it worked, but now it doesn't☹

![image](https://user-images.githubusercontent.com/6148597/121380587-fdd32680-c912-11eb-8dbf-bbba3e951535.png)
![image](https://user-images.githubusercontent.com/6148597/121380799-2d822e80-c913-11eb-95d4-602392b9dbf9.png)

**Comment by hbenl** [comment]
It seems that this extension isn't running at all (the Code Lenses in the second screenshot are not from this extension). Perhaps this is due to #210, which I just fixed. Please test it and tell me if it works for you.

**Comment by mpuls** [comment]
I have the same problem.

VSCode: 1.55.2
Test-Explorer: 2.20.4
Test Adapter Converter: 0.0.9

Reason seems to be:
```
[2021-06-14 09:07:01.016] [exthost] [error] Activating extension ms-vscode.test-adapter-converter failed due to an error:
[2021-06-14 09:07:01.022] [exthost] [error] TypeError: Cannot read property 'Running' of undefined
    at Object.<anonymous> (/home/Puls/.vscode/extensions/ms-vscode.test-adapter-converter-0.0.9/out/extension.js:1:3688)
    at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:4:1248)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at Module._load (internal/modules/cjs/loader.js:932:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:27791)
    at Function.E._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:24509)
    at Function.a._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:59194)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Function.t [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:5:101)
    at h._loadCommonJSModule (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:25918)
    at h._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:12016)
    at h._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:11072)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 9)
    at async Promise.all (index 0)
```

Since the Test Adapter Converter crashes, I don't know if the Test Explorer is responsible for this problem. Nonetheless, downgrading the Test Explorer to version 2.20.3 let the problem vanish.

**Comment by alambertt** [comment]
> It seems that this extension isn't running at all (the Code Lenses in the second screenshot are not from this extension). Perhaps this is due to #210, which I just fixed. Please test it and tell me if it works for you.

I updated the VSCOde and the bug is gone

> Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041
