### ISSUE TITLE
Unable to run tests from sub directories

### ISSUE THREAD

**Issue by sourcier** [hbenl/vscode-test-explorer#3]
I get the following error when I try to debug tests for a component in a sub dir:

```
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rrajaratnam/.vscode/extensions/hbenl.vscode-mocha-test-adapter-0.4.1/out/worker/runTests.js:19:5)
    at Module._compile (module.js:649:14)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Waiting for the debugger to disconnect...
```

My config:
```
"mochaExplorer.cwd": "app",
"mochaExplorer.require": [
    "ts-node/register"
],
"mochaExplorer.files": "app/test/**/*spec.ts",
```

I believe this is being caused by the mochaExplorer.cwd option not being honoured in the debug run, as tests work fine when not debugging.

**Comment by hbenl** [comment]
Moved to hbenl/vscode-mocha-test-adapter#1
