### ISSUE TITLE
Getting  "Error while loading tests" for python adapter

### ISSUE THREAD

**Issue by Casyfill** [hbenl/vscode-test-explorer#33]
when clicking on the text below getting this:
```
SyntaxError: Unexpected token I in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.parseTestSuites (/Users/philippk/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.0/src/pytest/pytestTestCollectionParser.ts:13:28)
    at PytestTestRunner.<anonymous> (/Users/philippk/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.0/src/pytest/pytestTestRunner.ts:95:24)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/philippk/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.0/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
```

**Comment by hbenl** [comment]
The stacktrace shows that this error is coming from the python adapter - please open an issue in their repository.
