### ISSUE TITLE
Cancelling a test run fails if one of the adapters throws an exception

### ISSUE THREAD

**Issue by xen22** [hbenl/vscode-test-explorer#50]
I have the following TestExplorer extensions installed:
- Mocha
- Python 
- Rust
- Catch2 and Google Test (C++)
- My own (unfinished) extension (in the debugger)

When I run my tests and then try to stop them, I get the following error in VSTest:
![image](https://user-images.githubusercontent.com/18519338/54512269-84a92b00-49b8-11e9-9a57-a4b19a34102c.png)

And here's the call stack, pointing to the Rust extension:

[2019-03-18 19:52:26.572] [exthost] [error] Error: Method not implemented.
    at RustAdapter.cancel (/home/ciprian/.vscode/extensions/swellaby.vscode-rust-test-adapter-0.5.0/src/rust-adapter.js:106:15)
    at TestAdapterDelegate.cancel (/home/ciprian/.vscode/extensions/hbenl.vscode-test-explorer-2.7.0/out/hub/testAdapterDelegate.js:25:22)
    at cancel.collections.forEach.collection (/home/ciprian/.vscode/extensions/hbenl.vscode-test-explorer-2.7.0/out/testExplorer.js:126:67)
    at Array.forEach (<anonymous>:null:null)
    at TestExplorer.cancel (/home/ciprian/.vscode/extensions/hbenl.vscode-test-explorer-2.7.0/out/testExplorer.js:126:26)
    at registerCommand (/home/ciprian/.vscode/extensions/hbenl.vscode-test-explorer-2.7.0/out/main.js:38:64)
    at d._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:160)
....

It would be better if the Test Explorer extension wrapped each individual call to the adapter.cancel() in a  try/catch block to allow non-failing extensions to continue the cancel operation.. Otherwise an extension that does not implement a certain operation (or has a bug) will stop the other extensions from working.

The same should be done for the other operations (e.g. run, load, etc)

**Comment by hbenl** [comment]
I have added try/catch blocks around all adapter calls that could influence other adapters. But most importantly I've learned that it's time for me to stop blindly trusting the adapters.
Thanks for the bugreport.
