### ISSUE TITLE
spawn c:\bin ENOENT

### ISSUE THREAD

**Issue by karamba121** [hbenl/vscode-test-explorer#73]
When I try to run my tests by anyway, getting this on console:

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn c:\bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 14:12:53] Connection to server got closed. Server will restart.

I'm on windows 10 using phpunit 8.1.3

**Comment by hbenl** [comment]
This is almost certainly an issue with the PHPUnit adapter, please post this issue in their repository.
